### ISSUE TITLE
strKey is not defined

### ISSUE THREAD

**Issue by joncodo** [friggframework/frigg#89]
ReferenceError: strKey is not defined
    at get (/Users/jon/Code/lefthook/canva--frigg/backend/.webpack/service/src/handlers/http/webpack:/frigg-app-back-end/node_modules/@friggframework/assertions/get.js:17:1)

asertions/get.js

```
const get = (o, key, defaultValue) => {
    const value = lodashGet(o, key, defaultValue);

    if (value !== undefined) {
        return value;
    }

    if (defaultValue === undefined) {
        throw new RequiredPropertyError({
            parent: this,
            key: strKey,
        });
    }

    return defaultValue;
};
```

strKey is not declared in this method. You only see this error on run so maybe I am the first one to hit it.

**Comment by seanspeaks** [comment]
Resolved
